### ISSUE TITLE
Load/Save niceties

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/pigg#103]
**Is your feature request related to a problem? Please describe.**
Help a user not lose work.

**Describe the solution you'd like**
If the user has made config change since starting or last loading a config, then on load warn that they are about to be lost and offer a cancel option.

If user clicks to exit and unsaved changes, warn them and on warning give option to save.

When loaded from file, show filename in UI or as part of window title (just name, not full path).

When loaded from file, prepopulate save with filename. Or allow a save, with no dialog....

If saving to a different file than loaded from, and exists, warn about overwriting a file and its contents will be lost.

**Additional context**
Post release 0.1

**Comment by andrewdavidmackenzie** [comment]
WDYT about working on for next-release @sundaram123krishnan ?
If you agree, then just add the label.

**Comment by sundaram123krishnan** [comment]
Sure, I feel like this functionality should be present in next release

**Comment by andrewdavidmackenzie** [comment]
Additional ideas:

- Chang config extension to be ".pigg" as piglet can load and apply them too.

- set ".pigg" as file extension to filter on in file browser when loading

- offer user to change/add file extension ".pigg" when saving a file
