### ISSUE TITLE
 Right Side Pin Visualization Missing and Pick List Placeholder Incorrect in Pin Layout View

### ISSUE THREAD

**Issue by sundaram123krishnan** [andrewdavidmackenzie/pigg#104]
**Describe the bug**
On the right side of the pin layout, input and output visualization is missing. Additionally, the pick list only shows "select" instead of "select function".

**To Reproduce**
1. Go to the pin layout view.
2. Observe the right side of the pin layout.
3. Notice that input and output visualizations are missing.
4. Also, notice that the pick list displays "select" instead of "select function".

**Expected behavior**
The right side of the pin layout should show input and output visualizations similar to the left side. The pick list should display "select function" instead of "select".

**Screenshots**
![image](https://github.com/andrewdavidmackenzie/pigg/assets/104441812/ee34a7df-7ffb-4adc-8fcd-574ca38f62eb)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Firefox Developer Edition
 - Version: 52.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrewdavidmackenzie** [comment]
I think it might be a fixed width of the parent, that is clipping it. They maybe there, but not visible?
