### ISSUE TITLE
Problems In Menu Buttons Rendering On Linux

### ISSUE THREAD

**Issue by sundaram123krishnan** [andrewdavidmackenzie/pigg#309]
In Linux, menu rendering problem is occuring.
The issue is further elaborated on https://github.com/iced-rs/iced_aw/issues/275

**Comment by sundaram123krishnan** [comment]
As this issue is in the renderer. Now the change in `Cargo.toml` seems to fix it.
In Pi 5B also it works fine, 
So closing the issue

**Comment by andrewdavidmackenzie** [comment]
@sundaram123krishnan is the iced issue fixed?
you closed it, but unclear if fixed or what....
so hard to know what to do with this one.

**Comment by sundaram123krishnan** [comment]
The issue was related to `tiny-skia`, so to fix we need to bump `iced` to `0.13`.

**Comment by andrewdavidmackenzie** [comment]
Assuming upgrade to 0.13 will indeed fix it...
Blocked by #466

**Comment by andrewdavidmackenzie** [comment]
Check if iced/iced_aw update fixes this, if not then move to a later release to re-check

**Comment by andrewdavidmackenzie** [comment]
With the changes after move to 0.13.1 we have lost hover higlighting (on linux) on all the menu buttons except the version one.

So, that's a problem (on linux) with menu bar / menu root highlighting, as the others are menus and the version on is just a button.

That might point to an issue in iced_aw?

@sundaram123krishnan

**Comment by andrewdavidmackenzie** [comment]
![screenshot-2024-10-31-09-30-56](https://github.com/user-attachments/assets/6cae6c37-2cda-4f26-9773-b7eb55ee2c2b)

**Comment by andrewdavidmackenzie** [comment]
Apart from [highlighting on hover](https://github.com/andrewdavidmackenzie/pigg/issues/560) issue, the original problem is fixed
