### ISSUE TITLE
Have layout react to pin layout field in HardwareDescription

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/pigg#397]
RPi pins alternate 1 on left, 2 on right and so on, so 40 is bottom left
Pico physical pins could 1-20 down left side, then 21-40 UP right side, with 40 top right

Thus, for the board layout to be correct, we need to do it differently for RPi and Pico.

We should send the layout as a field in HardwareDescription and then change the layout view to do one way or the other.

**Comment by andrewdavidmackenzie** [comment]
I have added this field: PinLayoutScheme in the HardwareDescription for pi_hw, fake_hw and porky in my pico-piglet branch.

@sundaram123krishnan would you like to work on the hardware layout view in this branch, changing how pins are laid out according to that field?

**Comment by andrewdavidmackenzie** [comment]
<img width="1106" alt="pi_pico_w_pinout" src="https://github.com/user-attachments/assets/8d5175e1-a7a7-4b42-be50-430a630cf09b">

**Comment by andrewdavidmackenzie** [comment]
Pi layout, using the Rows scheme

![pi](https://github.com/user-attachments/assets/7324639b-f3cc-4770-ada3-b9b3d16c53be)

**Comment by sundaram123krishnan** [comment]
Will do @andrewdavidmackenzie

**Comment by andrewdavidmackenzie** [comment]
This would be required prior to announcing/releasing Pico support is working
