### ISSUE TITLE
Add UI for Input sub options

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/pigg#40]
Input has Input pull-up sub-oprion with possible values:
- pullup
- pulldown
- none

Output: no sub-oprion needed, as we now have toggler to set value.

Show those Input as sub-options on the UI, either as part of the current widget, or as other widgets that can be used once the main mode it set.

**Comment by andrewdavidmackenzie** [comment]
We need to think how to handle these also.
So far I have only added for Inputs and Outputs and you can see the "(None)" in the name on the UI...
FYI @sundaram123krishnan

**Comment by sundaram123krishnan** [comment]
yaa i saw that, will think how to nest dropdown if it's possible

**Comment by andrewdavidmackenzie** [comment]
I think the ability to select pullup/pulldown is needed to have the basic "read an input" working correctly, otherwise we can't configure the pin correctly, and it won't read the correct value if (for example) a switch/button connecting it to ground is used with it... So, I added the release-0.1 label.

**Comment by sundaram123krishnan** [comment]
Agreed

**Comment by andrewdavidmackenzie** [comment]
We can simplify the Output option to avoid the None, Some(false), Some(true) sub-options, as there will be a toggler shown to set to true or false. So it can just say "Output"

**Comment by sundaram123krishnan** [comment]
Yes, makes sense

**Comment by andrewdavidmackenzie** [comment]
We could maybe do something visual with pull-up/down/none on the "wire" for the pin?

Might not be obvious what it does.

Can we add tooltips to the widgets to help I wonder?
