### ISSUE TITLE
cross compilation failing for aarch64 target in github actions

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/pigg#440]
e.g. https://github.com/andrewdavidmackenzie/pigg/actions/runs/10850493649

I might disable cross build, so CI is green, until we can fix this...

**Comment by andrewdavidmackenzie** [comment]
To work on this issue, uncomment the "cross" job in build_and_test.yml and then when working that change can be merged, so that CI should be passing before and after the change.

**Comment by sundaram123krishnan** [comment]
For now we can test on armv7 architecture, will open separate for fixing cross compilation for aarch64 target @andrewdavidmackenzie

**Comment by sundaram123krishnan** [comment]
I can also find a discussion related to it in `rust-skia`. 
https://github.com/rust-skia/rust-skia/discussions/959

**Comment by andrewdavidmackenzie** [comment]
Need to understand what is different in local vs. GH Actions...

**Comment by andrewdavidmackenzie** [comment]
Maybe we should try in local with intrument coverage?
