### ISSUE TITLE
Review names of I2C bus pins.

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/pigg#45]
Change names of some pins according to the I2C bus definitions from the rppal docs:

We're not supporting Raspberry Pi Model B Rev 1. So no I2C0.
Below applies for On Raspberry Pi models post Model B Rev 1

I2C1
SDA: BCM GPIO 2 (physical pin 3)
SCL: BCM GPIO 3 (physical pin 5)

I2C3
SDA: BCM GPIO 4 (physical pin 7)
SCL: BCM GPIO 5 (physical pin 29)

I2C4
SDA: BCM GPIO 8 (physical pin 24)
SCL: BCM GPIO 9 (physical pin 21)

I2C5
SDA: BCM GPIO 12 (physical pin 32)
SCL: BCM GPIO 13 (physical pin 33)

I2C6
SDA: BCM GPIO 22 (physical pin 15)
SCL: BCM GPIO 23 (physical pin 16)

**Comment by sundaram123krishnan** [comment]
is this required for 0.1 release? @andrewdavidmackenzie

**Comment by andrewdavidmackenzie** [comment]
I thought it would be good to get them "as correct as possible" for a first showing in public... and is easy.
