### ISSUE TITLE
Update readme before release-0.1

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/pigg#57]
What needs updating?

add a make target to install?
cargo install doesn't take --features options?

- [x] - General description that is forward looking, describe what is implemented already
- [x] - State of project at release-0.1
- [x] - Add something about roadmap, or reference a roadmap issue?
- [x] - Add screenshots and/or videos
- [x] - If readme is too long, move some to BUILDING.md?
- [x] - Add roadmap section as below, with links to issues
- [x] - Add a CI passing badge from GH Actions?
- [x] - Add a coverage badge from codecov.io, even if not great yet....motivate us to improve!

**Comment by andrewdavidmackenzie** [comment]
@sundaram123krishnan please comment things you think should be added or improved in the README

**Comment by sundaram123krishnan** [comment]
We can add example usage or provide some illustration @andrewdavidmackenzie

**Comment by andrewdavidmackenzie** [comment]
Maybe add an "Installing" section or INSTALLING file, although initially it will either be:
- cargo install pigg
- clone repo and cargo install (add a make target to install??)

**Comment by andrewdavidmackenzie** [comment]
Add a roadmap section with top-level ideas, comment that we want input and links to specific JIRAs with a roadmap lable.

Post-release-0.1
- review pin descriptions, maybe modify response to GUI depending on Pi HW detected
- code cleanup
- add tests for UI and get coverage up
- automation of release process and publishing packages
- improve visualizations of inputs
- add controls of outputs
- expand support beyond GPIO to I2c, uart etc,  with GUI support for config of pins in groups (e.g. I2C
- investigate remote GPIO over network and complete a "piglet" binary that acts as on-hw agent for GUI, or make it a build option of "piggui" (with a rename if it doesn't have GUI?)

**Comment by sundaram123krishnan** [comment]
Sounds good
