### ISSUE TITLE
Waveforms being clipped when running piggui on WIndows

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/pigg#663]
piggui for Windows, with porky on Pico W: top part of display not visible in either Physical or Logical layouts.

The timeline/histogram display for GPI0 does not display the On/High/True value of the Pin.

![image](https://github.com/user-attachments/assets/5091f6a5-d4af-4dc7-b6c1-f8f554e95ac1)

![image](https://github.com/user-attachments/assets/ec9f056f-970a-40e9-ba6e-e3e320ac011b)

**Comment by DeeJay** [comment]
Some more screenshots of failing timelines.

![Screenshot (6) crop](https://github.com/user-attachments/assets/fcdeee7d-5952-4f0b-952c-6dd21a5284f3)

![Screenshot (8) crop](https://github.com/user-attachments/assets/5abb2f02-836c-4a9c-961b-8272b92ff149)

![Screenshot (9) crop](https://github.com/user-attachments/assets/a2eb0dd4-6b1e-4682-882a-46e66603a318)





But this one looks correct.
![Screenshot (7) crop](https://github.com/user-attachments/assets/32f9d158-f5b4-4242-b566-a5cbe2be0397)


All produced using piggui on Windows 10, accessing an RPi Pico W running 'porky'.

**Comment by andrewdavidmackenzie** [comment]
More screenshots with problems

![image](https://github.com/user-attachments/assets/5063f197-89f9-4847-b183-edc432682a22)

![image](https://github.com/user-attachments/assets/4c31de38-e498-43e6-ac8f-97212f9ed2ab)

![image](https://github.com/user-attachments/assets/0f6b2582-a084-4895-a303-4c1c8e703804)


But sometimes is OK

![image](https://github.com/user-attachments/assets/6638a170-d07e-4027-a4e7-fb3f448770c2)

Thanks @DeeJay

**Comment by andrewdavidmackenzie** [comment]
I have now been able to build on run on Windows 11 inside Parallels Desktop on my Mac.

In the @bcp@ layout (connected to internal fake HW) I cannot get clipping, at top nor bottom.

<img width="1058" alt="Screenshot 2024-12-17 at 9 49 14 AM" src="https://github.com/user-attachments/assets/caafa0ee-ba80-4733-ae23-cdf059d3bc30" />

<img width="831" alt="Screenshot 2024-12-17 at 9 53 26 AM" src="https://github.com/user-attachments/assets/4b0137b0-b6bf-4ae3-b5d2-14a8115531e3" />

It looks like @DeeJay you connected to a Pico W in the screenshots?

I haven't been able to do that yet from Windows, but will try.

I see you are on Windows 10 and I am on Windows 11... I wonder if that is the difference?

@DeeJay can you please check
- also happens when you just use the internal "fake" hardware option, any way to reproducde on that?
- do you have any access to a Windows 11 machine, to check if also happens there for you
- Any other suggestions how I could reproduce it, thanks...

**Comment by andrewdavidmackenzie** [comment]
(I am use HEAD of master, so it is possible there is a difference there, I'll try 0.5.0 tag also...)

**Comment by andrewdavidmackenzie** [comment]
I can see that there is a change in height of the row, when configuring as an input or output.
The waveform must be slightly taller than the space in the row for other things, and that could cause a problem.

**Comment by andrewdavidmackenzie** [comment]
I have made changes in the PR https://github.com/andrewdavidmackenzie/pigg/pull/748
which I think are a good idea anyway, and *may* help here. 
But since I cannot reproduce, it's hard to know.

@DeeJay are you able to build and run HEAD of master (when I merge the PR) to verify if fixes it, or will you have to wait for a release?

**Comment by andrewdavidmackenzie** [comment]
"Smart commit message" was too smart - re-opened pending your confirmation...

**Comment by andrewdavidmackenzie** [comment]
@DeeJay sorry for bugging you, just tracking this issue to see if those changes fixed it or not.
Let me know if you are able to check with master. If not we'll do the release later and maybe able to confirm then...

**Comment by DeeJay** [comment]
Sorry to seem unhelpful after flagging a possible issue, but my comment in #656 3 weeks ago still applies. "For the time being the conclusion is that I will not be able to test a fix for Windows if it requires building from source."

Other than Raspberry Pi boards running RasPiOS I only have access to Win10 machines: they are underpowered and short of memory and filestore - at this stage in their lifecycle I am reluctant to risk their stability by installing a development toolchain that I would not understand.

I will undertake to look at behaviour with the fake h/w stub using the release of v0.5.0 under Win10, but it may not be for a day or so.

**Comment by andrewdavidmackenzie** [comment]
OK, no worries. Sorry I forgot you said that.
I'll take a punt, assume it's fixed, and after I release 0.6.0 - if then you could test a windows binary, that would be great, and I can re-open the issue if needed.
thanks.
